[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install uv",
  "uv sync --frozen --no-dev"
]

[phases.build]
cmds = []

[start]
cmd = "uv run uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
